spring.data.mongodb.uri: mongodb+srv://awesome-app-bff-admin:password@test-orvxq.mongodb.net/awesome-app-bff
spring.session.store-type: mongodb
server.port: 80
internal.lb.uri: http://localhost
users.api.url: ${internal.lb.uri}:8081/api/v1/users
